#!/usr/bin/env sh

# Originally taken from https://coderwall.com/p/moabdw and modified a little

HOST="qs0.qsapp.com"
HOST_DIRECTORY="~/public_html/"
ARGS="-avuz --delete --progress --exclude-from=.gitignore --exclude=.git --exclude=.gitignore"

if [ "$1" = "--help" ] || [ $# -eq 0 ]
    then
        echo "\nQSApp.com deploy script
    
        Options:
    
        -l       live deploy: push the changes to the server
        -n       dry-run
        "
        exit
fi

if [ "$1" != "-l" ] && [ "$1" != "-n" ]
    then
        echo "Error running script - maybe you didn't use the right argument?\nSee deploy --help for more info"
        exit
fi

if [ "$1" = "-n" ]
    then
        echo "Running dry-run"
        ARGS="--dry-run $ARGS"
elif [ "$1" = "-l" ]
    then
        echo "Running actual deploy"
fi


rsync ${ARGS} -e "ssh -p22" ./ ${HOST}:${HOST_DIRECTORY}
