// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "common": {
    "buttons": {
      "close": "Close",
      "copied": "Copied!",
      "copy": "Copy",
      "download": "Download",
      "downloadQuicksilver": "Download Quicksilver",
      "joinDiscussions": "Join Discussions",
      "learnMore": "Learn More",
      "readManual": "Read the Manual",
      "reportIssue": "Report Issue",
      "viewFaq": "View FAQ"
    },
    "footer": {
      "links": {
        "changelog": "Changelog",
        "comparison": "Quicksilver vs Alfred",
        "developerDocs": "Developer Docs",
        "donate": "Donate",
        "faq": "FAQ",
        "getHelp": "Get Help",
        "github": "GitHub",
        "plugins": "Plugins",
        "reportIssue": "Report an Issue",
        "translate": "Translate",
        "userManual": "User Manual"
      },
      "sections": {
        "community": "Community",
        "documentation": "Documentation",
        "product": "Product",
        "support": "Support"
      },
      "tagline": "Quicksilver is free and open source software."
    },
    "homebrew": {
      "description": "You can also install Quicksilver using Homebrew:",
      "title": "Install via Homebrew"
    },
    "language": {
      "en": "English",
      "label": "Language",
      "zh": "简体中文"
    },
    "nav": {
      "donate": "Donate",
      "download": "Download",
      "plugins": "Plugins",
      "support": "Support"
    }
  },
  "comparison": {
    "badge": "Comparison",
    "cta": {
      "description": "Download for free and experience the power of a true action-based launcher.",
      "title": "Ready to try Quicksilver?"
    },
    "description": "Searching for the best Mac launcher? Here's why Quicksilver is the choice for power users who want total control—for free.",
    "intro": {
      "paragraph1": "Both Quicksilver and Alfred are keyboard-driven productivity apps for macOS that help you launch applications, find files, and automate tasks. Alfred launched in 2010 and has become popular for its polished interface and workflow system.",
      "paragraph2": "Quicksilver pioneered this category back in 2003 and takes a fundamentally different approach: while Alfred focuses on <em>finding</em> things, Quicksilver focuses on <em>doing</em> things. Its noun-verb-object model lets you chain actions together fluidly—and every feature ships free and open source."
    },
    "table": {
      "clipboardHistory": "Clipboard History",
      "contactActions": "Contact Actions",
      "customThemes": "Custom Themes",
      "feature": "Feature",
      "fileActions": "Advanced File Actions",
      "globalHotkeys": "Global Hotkeys & Triggers",
      "included": "Included",
      "musicControl": "Music Control",
      "paid": "Paid",
      "philosophy": "Philosophy",
      "philosophyAlfred": "Search-based",
      "philosophyQs": "Action-based",
      "price": "Price",
      "priceFree": "Free (Open Source)",
      "pricePaid": "Free / ~£34 Powerpack",
      "proxyObjects": "Proxy Objects",
      "proxyObjectsAlfred": "Requires Workflows",
      "proxyObjectsQs": "Core Feature",
      "searchIndex": "Search Index",
      "searchIndexAlfred": "Spotlight Dependent",
      "searchIndexQs": "Bare Metal (Fast)"
    },
    "title": "Quicksilver vs. Alfred",
    "whySection": {
      "act": {
        "description": "Alfred searches. Quicksilver acts. Select a file → Email it → To a colleague. All without touching the mouse.",
        "number": "1",
        "title": "Act, Don't Just Search"
      },
      "context": {
        "description": "Use Proxy Objects to instantly act on your current Finder selection. Select a file, hit a hotkey, move it instantly.",
        "number": "4",
        "title": "Context Aware"
      },
      "free": {
        "description": "No 'Powerpacks,' no paid upgrades. Clipboard history, theming, deep system control—all free forever.",
        "number": "2",
        "title": "Truly Free & Open"
      },
      "spotlight": {
        "description": "Quicksilver builds its own catalog. Lightning fast and works instantly, even if Spotlight is broken or indexing.",
        "number": "3",
        "title": "Spotlight Independent"
      },
      "title": "Why Quicksilver?"
    }
  },
  "donate": {
    "amount": {
      "currency": "USD",
      "label": "Select an amount",
      "other": "Other",
      "placeholder": "Enter amount"
    },
    "card": {
      "body1": "Quicksilver is free and open source and will always remain that way. No 'powerpack' or 'pro' version – just good healthy open source.",
      "body2": "That said, we rely on donations to help cover hosting costs, domain renewals, and development resources.",
      "description": "Support the Quicksilver Project by donating today.",
      "title": "Make a Donation"
    },
    "description": "Quicksilver is free and open source, developed by volunteers. Your donation helps keep the project alive.",
    "otherWays": {
      "contribute": {
        "description": "Help fix bugs or add new features on GitHub.",
        "title": "Contribute Code"
      },
      "documentation": {
        "description": "Help others learn Quicksilver by improving the manual.",
        "title": "Improve Documentation"
      },
      "reportIssues": {
        "description": "Found a bug? Let us know on the issue tracker.",
        "title": "Report Issues"
      },
      "title": "Other Ways to Help",
      "translate": {
        "description": "Help translate Quicksilver into your language.",
        "title": "Translate Quicksilver"
      }
    },
    "paypal": {
      "button": "Donate with PayPal"
    },
    "title": "Support Quicksilver"
  },
  "faq": {
    "description": "Everything you need to know about Quicksilver.",
    "questions": {
      "cost": {
        "answer": "Quicksilver is completely free. There's no paid version, no subscription, and no features locked behind a paywall. It's free and open source software, developed by volunteers who believe great tools should be accessible to everyone.",
        "question": "How much does Quicksilver cost?"
      },
      "developers": {
        "answer": "Quicksilver is open source software, developed by a group of volunteer contributors.",
        "question": "Who are the developers behind Quicksilver?",
        "viewContributors": "View who's contributed to the software on GitHub"
      },
      "plugins": {
        "answer": "Make sure you have the appropriate plugin installed. Many features come from plugins which you can browse and install from within Quicksilver's preferences. If it's something in the catalog you don't see, make sure it's enabled and scanned.",
        "question": "Why don't I see a feature or plugin I expected?"
      },
      "spotlight": {
        "answer": "No. Spotlight finds things, but all it lets you do is open them. Quicksilver finds things and then lets you do all sorts of stuff with them — move files, send emails, control apps — with just a keystroke or two.",
        "learnMore": "Learn more in the manual",
        "question": "Doesn't Spotlight make Quicksilver unnecessary?"
      }
    },
    "seeMore": {
      "link": "See all FAQs →",
      "prompt": "Have more questions?"
    },
    "title": "Frequently Asked Questions",
    "whyChoose": {
      "free": {
        "description": "No \"powerpack\", no \"pro\" version, no subscription. Every feature is free.",
        "title": "100% Free Forever"
      },
      "intro": "There are many launcher apps for macOS, but Quicksilver stands apart:",
      "openSource": {
        "description": "Fully open source and community-maintained. Audit the code, contribute features, or fork it.",
        "title": "Open Source"
      },
      "original": {
        "description": "Quicksilver pioneered the launcher concept in 2003, inspiring every app that followed.",
        "title": "The Original Mac Launcher"
      },
      "privacy": {
        "description": "Quicksilver doesn't phone home, collect analytics, or track your usage. Your data stays on your Mac.",
        "title": "No Tracking, Complete Privacy"
      },
      "title": "Why Choose Quicksilver?"
    }
  },
  "home": {
    "cta": {
      "description": "Download Quicksilver today and discover a faster way to work.",
      "title": "Ready to supercharge your Mac?"
    },
    "features": {
      "description": "Quicksilver lets you start applications, manipulate files, and much more — all from your keyboard.",
      "extensible": {
        "description": "Hundreds of plugins extend Quicksilver's capabilities to work with your favorite apps.",
        "title": "Extensible"
      },
      "instantLaunch": {
        "description": "Launch applications, open files, and access bookmarks with just a few keystrokes.",
        "title": "Instant Launch"
      },
      "openSource": {
        "description": "Free forever. Actively maintained by a passionate community of developers.",
        "title": "Open Source"
      },
      "powerfulActions": {
        "description": "Move, copy, email, or compress files. Send messages. Control iTunes. The possibilities are endless.",
        "title": "Powerful Actions"
      },
      "smartLearning": {
        "description": "Quicksilver learns your habits and adapts to show you what you need, when you need it.",
        "title": "Smart Learning"
      },
      "title": "Lightning Fast Productivity",
      "triggers": {
        "description": "Assign keyboard shortcuts or mouse gestures to instantly run any action.",
        "title": "Triggers"
      }
    },
    "hero": {
      "allVersions": "All versions",
      "description": "Quicksilver is a fast macOS productivity application that gives you the power to control your Mac quickly and elegantly.",
      "homebrewInstall": "Install via Homebrew",
      "tagline": "Act without doing",
      "version": "Version {{version}} · macOS {{minOS}}+"
    },
    "interfaces": {
      "description": "Choose from multiple interfaces, styles and colors to fit your rhythm.",
      "footer": "10+ interfaces to choose from, with color theming built in!",
      "title": "Multiple Interfaces tailored to you"
    },
    "plugins": {
      "description": "Supercharge Quicksilver with plugins that integrate with your favorite apps and workflows.",
      "exploreAll": "Explore All Plugins",
      "featurePreviewAlt": "Plugin feature preview",
      "items": {
        "browsers": {
          "description": "Control Safari, Chrome, and Firefox. Search bookmarks and history.",
          "title": "Browsers"
        },
        "calculator": {
          "description": "Perform calculations instantly and copy results to clipboard.",
          "title": "Calculator"
        },
        "calendar": {
          "description": "Create events and reminders without leaving your keyboard.",
          "title": "Calendar & Reminders"
        },
        "clipboard": {
          "description": "Access clipboard history and store items for quick access.",
          "title": "Clipboard & Shelf"
        },
        "emojis": {
          "description": "Search and insert emojis anywhere with a quick shortcut.",
          "title": "Emojis"
        },
        "images": {
          "description": "Resize, crop, and convert images directly from Quicksilver.",
          "title": "Image Manipulation"
        },
        "mail": {
          "description": "Send emails directly from Quicksilver with Apple Mail or Gmail.",
          "title": "Mail"
        }
      },
      "selectInterface": "Select {{name}} interface",
      "title": "Infinitely Extend with Plugins"
    }
  },
  "plugins": {
    "buildYourOwn": "Build your own!",
    "changelog": {
      "close": "Close",
      "title": "{{name}} Changelog",
      "version": "Version {{version}}"
    },
    "description": "Extend Quicksilver with plugins for your favorite apps and services.",
    "search": {
      "noResults": "No plugins found matching \"{{query}}\"",
      "placeholder": "Search plugins...",
      "resultCount": "{{count}} plugins available" | "search.resultCount" | "search.resultCount",
      "resultCountFiltered": "{{count}} plugins matching \"{{query}}\"" | "search.resultCountFiltered" | "search.resultCountFiltered"
    },
    "title": "Plugins"
  },
  "support": {
    "description": "Need help with Quicksilver? Here are the best ways to get support.",
    "discussions": {
      "body": "The GitHub Discussions forum is the best place to ask questions, share tips, and connect with other Quicksilver users.",
      "description": "Ask questions and get help from the community",
      "title": "GitHub Discussions"
    },
    "documentation": {
      "body": "The manual covers everything from installation to advanced triggers and plugins. It's the best place to start learning.",
      "description": "Start with the official Quicksilver Manual",
      "title": "Documentation"
    },
    "faq": {
      "body": "Find answers to common questions about Quicksilver, troubleshooting tips, and learn why Quicksilver might be the right choice for you.",
      "description": "Frequently asked questions",
      "title": "FAQ"
    },
    "issues": {
      "body": "If you've found a bug, please report it on GitHub Issues. Include your macOS version, Quicksilver version, and steps to reproduce.",
      "description": "Found something wrong? Let us know",
      "title": "Report a Bug"
    },
    "title": "Get Help"
  }
}

export default Resources;
