name: Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Write SSH key
      run: 'echo "$SSH_KEY" > key'
      env:
        SSH_KEY: ${{secrets.SSH_KEY}}
    - name: Pull changes
      env:
        SERVER: ${{ secrets.SERVER }}
        PORT: ${{ secrets.PORT }}
      run: |
        ssh "${SERVER}" -p "${PORT}" -i ./key 'git -C www pull --dry-run -vv'
